stages:
  test:
    cmd: echo "Hello testing"

  train_data:
    cmd: |
      dvc pull
      python train.py
    deps:
    - dvc.yaml
    - train.py
    outs:
    - Dataset.csv
    metrics:
    - metrics.json:
        cache: false
