stages:
  test:
    cmd: echo "Hello testing"

  get_data:
    cmd: dvc pull
    outs:
    - Dataset.csv

  train_data:
    cmd: python train.py
    deps:
    - Dataset.csv
    outs:
    - model.pkl
    metrics:
    - metrics.json:
        cache: false
